channels:
  - conda-forge
dependencies:
  - python ~= 3.9.0
  - dask
  - distributed
  - pip
  # ome: minimal dependencies required to use the Python API
  - pandas
  - tensorflow
  - pip:
    - ome-zarr
    - dask-image
    - stardist==0.8.1
    # dependency to save the labels as geojson file
    - geojson
